Repository dwavesystems/dwave-networkx, pull requests merged in 2018-02, with the labels that each got.

#20 Proposal for navigation template
  README.md
  README.rst
  docs/_static/ChimeraUnitCell.png
  docs/_static/Cover.png
  docs/_static/Problem_MapColoring.png
  docs/_static/chimera_layout_0-rightside.png
  docs/_static/find_chimera-unitcell.png
  docs/about_dwave.rst
  docs/conf.py
  docs/contributing.rst
  docs/dwave.rst
  docs/glossary.rst
  docs/index.rst
  docs/installation.rst
  docs/license.rst
  docs/ocean.rst
  docs/reference/algorithms/coloring.rst
  docs/reference/algorithms/cover.rst
  docs/reference/algorithms/elimination_ordering.rst
  docs/reference/algorithms/index.rst
  docs/reference/algorithms/matching.rst
  docs/reference/algorithms/max_cut.rst
  docs/reference/algorithms/packing.rst
  docs/reference/algorithms/social.rst
  docs/reference/default_sampler.rst
  docs/reference/drawing.rst
  docs/reference/generators.rst
  docs/reference/index.rst
  dwave_networkx/algorithms/coloring.py
  dwave_networkx/algorithms/cover.py
  dwave_networkx/default_sampler.py
  dwave_networkx/drawing/chimera_layout.py
  dwave_networkx/generators/chimera.py
Labels: enhancement

#34 Version
  dwave_networkx/algorithms/tests/test_coloring.py
  dwave_networkx/algorithms/tests/test_matching.py
  requirements.txt
  setup.py
Labels: bug

#21 New examples
  dwave_networkx/examples/min_vertex_color.py
  dwave_networkx/examples/min_vertex_cover.py
Labels: enhancement

#37 Fix bug where chimera_graph only accepts integers
  dwave_networkx/generators/chimera.py
  dwave_networkx/generators/tests/test_chimera.py
Labels: bug

#39 Update setup.py extras to include matplotlib and numpy
  .coveragerc
  .travis.yml
  setup.py
Labels: bug, enhancement
