Repository dwavesystems/dwave-networkx, pull requests merged in 2019-04, with the labels that each got.

#104 added note in pegasus docs to address issue 100
  dwave_networkx/generators/pegasus.py
Labels: documentation, enhancement

#102 Visualize crosses
  dwave_networkx/drawing/pegasus_layout.py
  dwave_networkx/drawing/tests/test_pegasus_layout.py
Labels: enhancement

#107 TSP no longer treats the graph as directed
  docs/reference/algorithms/tsp.rst
  dwave_networkx/algorithms/tests/test_tsp.py
  dwave_networkx/algorithms/tsp.py
Labels: bug

#109 Fix pegasus degree 6 --> 15
  docs/intro.rst
Labels: documentation

#112 Draw qubit graph yield
  dwave_networkx/drawing/chimera_layout.py
  dwave_networkx/drawing/pegasus_layout.py
  dwave_networkx/drawing/qubit_layout.py
  dwave_networkx/drawing/tests/test_chimera_layout.py
  dwave_networkx/drawing/tests/test_pegasus_layout.py
Labels: enhancement
